# Generated by Django 3.0.1 on 2019-12-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('birth_place', models.CharField(max_length=50)),
                ('death', models.DateField(blank=True)),
                ('is_dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateField()),
                ('based_on', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('related_url', models.URLField(max_length=300)),
                ('created_with', models.ManyToManyField(blank=True, to='newapp.Scientist')),
            ],
        ),
        migrations.AddField(
            model_name='scientist',
            name='theories',
            field=models.ManyToManyField(to='newapp.Theory'),
        ),
    ]
